/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
static yyconst short int yy_accept[519] =
    {   0,
        0,    0,   60,   53,   57,   54,   58,   26,   27,   29,
       23,   31,   34,   32,   33,   22,   36,   36,   30,   24,
       35,   25,   39,   39,   39,   39,   39,   39,   39,   39,
       28,   53,   53,   53,    0,   53,    0,    0,    0,   53,
       53,   10,   53,   53,   21,    0,    0,   13,    0,    0,
        0,    0,    0,    0,   19,   15,   17,   16,   18,   37,
       53,   53,   20,    0,   36,   53,   38,   36,   38,   36,
       11,    9,   12,   39,   39,   39,   39,   39,    3,   39,
       39,   39,   39,   14,   41,   52,   44,   50,   46,   48,
       47,   49,   51,   42,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   40,   41,   41,   43,   45,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   40,   52,   52,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   40,   45,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   40,   50,   50,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   40,   48,   48,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   40,   49,   49,    0,   53,    0,   53,   53,    0,

       53,    0,    0,    0,   53,   53,   50,   53,   53,   53,
       56,   53,   53,   56,   53,   56,   56,   56,   53,   53,
       51,   53,   53,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   40,   51,   51,   38,   38,   36,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   40,   42,   42,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   40,   43,   43,   39,   39,   39,    4,   39,   39,
       39,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   52,   44,   50,   46,
       48,   47,   49,   51,   42,   43,   45,   41,   44,   44,
       44,   44,   44,   44,   44,   42,   40,   43,   44,   41,
       50,   44,   50,   46,   48,   47,   49,   50,   42,   43,
       45,   41,   46,   44,   46,   46,   46,   46,   46,   42,
       40,   43,   45,   41,   48,   44,   48,   48,   46,   47,
       48,   48,   42,   43,   45,   41,   47,   44,   47,   47,
       46,   47,   47,   42,   40,   43,   45,   41,   49,   44,
       49,   49,   46,   48,   47,   49,   42,   43,   45,    0,
       37,   53,    0,   41,   52,    0,    0,   44,    0,    0,

        0,    0,    0,    0,   53,   46,   48,   47,   49,   51,
       42,   40,   43,   45,   41,   52,   56,   56,   44,   56,
       56,   56,   56,   56,   56,   50,   46,   48,   47,   49,
       42,   40,   43,   45,   41,   51,   44,   51,   50,   46,
       48,   47,   49,   42,   43,   45,   41,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       41,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       42,   43,   39,    2,   39,   39,    6,   39,   41,   45,
       45,   45,   44,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   42,   40,   43,   53,   55,   55,
       45,   45,    1,    7,   39,    8,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    1,    1,    6,    7,    1,    4,
        4,    8,    9,   10,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   22,   21,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   24,   23,   23,
        1,    1,    1,    1,   23,    1,   25,   21,   26,   27,

       28,   29,   23,   30,   31,   23,   23,   32,   23,   33,
       34,   23,   23,   35,   36,   37,   38,   39,   40,   41,
       23,   23,    4,   42,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    2,    3,    2,    1,    1,    2,    1,    2,    2,
        2,    2,    1,    4,    4,    4,    2,    1,    2,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    5,
        4,    1
    } ;

static yyconst short int yy_base[526] =
    {   0,
        0,    0, 1095,    0, 1167, 1167, 1167,   38, 1075,   76,
     1074,   45, 1167,   52,   46,   57,  118,   76, 1085, 1072,
       59, 1071,  160,  202,   35,   40,   68,   45, 1055, 1058,
       56,    0, 1068, 1067, 1078, 1065,   90,   92, 1076, 1063,
     1062,  240, 1061,   85,  278,  101,  103,  316,  106,  109,
      155,  156,  157,   70,  354,  392,  430,  468,  506,  155,
      548,  590,  628,   91,  143,  171,  670,  712,    0,  173,
      750,  788,  826, 1045,    0,   81,  101, 1043, 1041,  145,
      156,  160, 1043,  864,  185,  192, 1066,  194,  187,  200,
      110,  205,  206,  207, 1053, 1051,  214, 1050,  218,  212,

     1049, 1048, 1046,    0, 1043,  186,  219,  213, 1042, 1041,
      222, 1038,  231,  224, 1037, 1036, 1035,    0, 1034,  220,
     1033, 1032,    0, 1031,  245,  250,    0, 1030, 1029, 1028,
     1027, 1003,  252,  258, 1025, 1024,  249, 1023,  257,  256,
     1022, 1021, 1020,    0, 1019,  251, 1018, 1013,  273, 1012,
        0,  262, 1011, 1007, 1000,  999,  998,  259,  997,  996,
      287,  995,  290,  291,  994,  993,  992,    0,  991,  269,
      990,  989,  296,  988,  295,    0,  987,  986,  985,  984,
      983,  288,  982,  981,  298,  980,  299,  320,  975,  974,
      973,    0,  969,  300,  329,  902,  973,  961,  960,  940,

      965,  345,  330,  970,  957,  956,  349,  955,  313,  978,
        0,  954,  953, 1016,  952,  368,  369,  963,    0,  950,
      350,  949,  328,  948,  947,  371,  946,  307,  370,  945,
      944,  943,    0,  942,  360, 1058,    0,    0,  937,  936,
      375,  935,  374,  373,  931,  924,  923,    0,  922,  366,
      921,  920,  931,  918,  397,  396,    0,  917,  916,    0,
      915,  891,  913,  912,  406,  911,  405,  407,  910,  909,
      908,    0,  907,  398,  238,  393,  147,  891,  312,  395,
      892,  904,  899, 1096,  898,  437,  412,  909,  893,  886,
      413,  885,    0,    0,    0,  426,    0,  442,    0,  441,

        0,    0,    0,    0,  411,    0,    0,  447,    0,  446,
        0,  448,    0,    0,    0,    0,  449,  884,  883,  882,
      473,  881,  451,  880,  879,  878,  877,  876,  852,    0,
        0,  450,    0,  474,    0,  452,    0,    0,    0,    0,
      459,  873,  872,  477,  871,  870,  478,  855,  837,  808,
      807,  766,  479,    0,    0,  483,    0,    0,  485,  484,
        0,    0,    0,    0,  480,  763,  697,  501,  574,  526,
      497,  519,  512,  488,  481,  445,  486,    0,    0,  520,
        0,    0,  521,    0,  518,    0,    0,    0,  490,  519,
      527,  445,  340,  631,  635,  636,  637,    0,  644,  642,

      645,  646,  653,  270,  409,  660,  655,  666,  661,  674,
      675,  677,  679,  647,  680,  684,  685,  688,    0,  690,
      695,  704,  712,  753,  344,  757,  764,  758,  767,  768,
      772,  783,  791,  682,    0,    0,  796,    0,    0,  527,
        0,  689,    0,    0,    0,  687,    0,    0,  797,    0,
        0,  696,    0,  769,    0,    0,    0,  747,    0,    0,
      388,    0,  800,    0,  801,    0,    0,    0,    0,  349,
        0,    0,  804,    0,    0,  805,    0,  802,    0,    0,
        0,  798,  510,  279,  747,  624,  245,  206,  822,  829,
      835,  840,    0,  842,  843,  844,  845,  191,  846,    0,

      809,    0,  847,  867,  868,  869,  874,    0, 1167,  848,
      815,  818,   52,   34,  688,    0,   14, 1167, 1138, 1142,
     1144, 1149, 1151, 1156, 1161
    } ;

static yyconst short int yy_def[526] =
    {   0,
      518,    1,  518,  519,  518,  518,  518,  519,    8,  518,
        8,   10,  518,   10,   10,    8,  518,   17,   10,    8,
       10,    8,  520,  520,   24,   24,   24,   24,   24,  521,
        8,  519,    8,    8,   10,    8,   12,   14,   10,    8,
        8,  518,    8,    8,  518,   10,   10,  518,   10,   10,
       10,   10,   10,   10,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,   17,   17,  522,  518,  523,   17,
      518,  518,  518,   24,  521,   24,   24,   24,   24,   24,
       24,   24,  521,    8,   10,   10,   10,   10,   12,   12,
       14,   14,   14,   14,   42,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   42,   42,   14,    8,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   14,   10,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,  518,   61,  524,   61,   61,  524,

       61,  200,  200,  200,   61,   61,  200,   61,   61,   62,
      525,   62,   62,  525,   62,  214,  214,  214,   62,   62,
      214,   62,   62,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,  522,  523,   68,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   24,   24,   24,   24,   24,   24,
      521,   84,   84,  518,   84,  284,  284,  284,   84,   84,
      284,   84,   84,   42,   42,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   42,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,  518,
      518,  196,  524,  200,  200,  200,  200,  200,  200,  200,

      200,  200,  200,  200,    8,  200,  200,  200,  200,  200,
      200,  200,  200,   61,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,   62,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   24,   24,   24,   24,   24,  521,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  286,

      286,  287,  287,  287,  287,  287,  287,  519,  518,   10,
      200,  214,   24,   24,   24,  521,   24,    0,  518,  518,
      518,  518,  518,  518,  518
    } ;

static yyconst short int yy_nxt[1210] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   19,   20,   21,   22,
       23,   23,   23,   23,   23,   24,   23,   25,   26,   23,
       27,   23,   23,   23,   28,   23,   23,   23,   29,   30,
       23,   31,   33,   34,   35,   36,   37,   74,   38,   39,
       40,   35,   35,   56,   39,   41,   42,   43,   35,   60,
       60,   60,   58,   57,   61,   35,   77,   74,   74,   62,
       59,   78,   81,   74,   52,   63,   35,   72,   74,   44,
       46,   47,   48,   49,   37,   74,   38,   39,   50,   70,
       70,   70,   39,   51,   52,   53,   79,   84,   89,   67,

       80,   74,   91,   52,   60,   60,   60,   35,   90,   35,
       92,  134,   35,  275,   74,   35,   67,   54,   32,   85,
       91,   86,   32,   32,   88,   32,  108,   93,   92,   64,
       32,   65,   65,   66,   74,   32,  276,   32,   67,   67,
       67,   68,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   69,   68,   32,
       32,   35,   35,   35,   32,   32,   67,   32,   60,   60,
       60,  485,   32,   94,  133,  107,  195,   32,   74,   32,
       74,  278,  195,   67,   66,   66,   70,   70,   70,   74,
      280,   35,  279,   74,   67,   89,   67,  284,   35,   75,

       35,   32,   32,  133,  294,   90,   32,   32,   37,   32,
      133,   67,  133,   67,   32,   38,   38,   38,  133,   32,
      296,   32,  300,  133,  133,  133,  298,  305,  308,   38,
      301,   52,  294,  516,  312,   76,  299,  133,  307,  310,
      307,   75,  313,   32,   95,   96,   97,   98,   99,  311,
      100,  101,  102,  321,  108,  332,  101,  103,  104,  105,
      323,  317,   38,  322,   35,  334,  336,  333,  324,  333,
      133,   74,  347,  483,  337,  335,  200,  345,   74,  344,
      348,  106,  109,  110,  111,  112,  113,  357,  114,  115,
      116,  345,  341,  356,  115,  117,  118,  119,  359,  134,

      353,  360,  368,  371,  380,  357,  369,  383,  357,  361,
      365,  511,   74,  372,  369,  440,  381,  384,  381,  120,
      121,  122,  123,  124,  125,  441,  126,  127,  128,  377,
      385,  402,  127,  129,  130,  131,  200,  390,  381,  390,
      408,  389,  391,  391,  391,   74,  423,  393,  409,  486,
      214,  200,  509,  406,  414,  200,  214,  132,  135,  136,
      137,  138,  139,  407,  140,  141,  142,  412,  432,  434,
      141,  143,  144,  145,  214,  214,  427,  437,  438,  429,
      442,  449,  452,  454,  450,  512,  428,  430,  443,  438,
      470,  455,  453,  450,  461,  146,  147,  148,  149,  150,

      151,  446,  152,  153,  154,  463,  465,  458,  153,  155,
      156,  157,  473,  476,  466,  464,  474,  478,  284,  284,
      484,  487,  502,  477,  474,  479,   74,   93,   74,  294,
      503,  506,  296,  158,  159,  160,  161,  162,  163,  482,
      164,  165,  166,  284,  294,  500,  165,  167,  168,  169,
      298,  300,  305,  308,  310,  501,  332,  508,  312,  301,
      299,  323,  336,  375,  311,  307,  313,  307,  333,  324,
      337,  170,  171,  172,  173,  174,  175,  333,  176,  177,
      178,  321,  334,  344,  177,  179,  180,  181,  347,  356,
      317,  322,  335,  359,  360,  345,  348,  345,  357,  375,

      341,  357,  361,  357,  369,  371,  375,  368,  381,  182,
      183,  184,  185,  186,  187,  372,  188,  189,  190,  369,
      353,  365,  189,  191,  192,  193,  380,  377,  385,  383,
      375,  389,  391,  391,  391,  440,  381,  375,  381,  384,
      391,  391,  391,   74,  375,  441,  513,  194,  196,  197,
      197,  197,  198,  199,  200,  201,  202,  197,  203,  204,
      205,  196,  196,  196,  204,  206,  207,  208,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  197,  196,  209,
      210,  211,  375,  211,  212,  213,  214,  215,  216,  211,

      217,  218,  219,  210,  210,  210,  218,  220,  221,  222,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  211,
      210,  223,  224,  225,  226,  227,  228,  200,  229,  230,
      231,  200,  200,  200,  230,  232,  233,  234,  200,  412,
      200,  200,  200,  412,  394,  395,  510,   74,  515,  200,
      410,  200,  207,  411,  412,  402,  200,  200,  406,  235,
       32,  413,  200,  412,   32,   32,  408,   32,  407,  412,
      200,  200,   32,  200,  409,  200,  214,   32,  414,   32,
      214,  214,  412,  412,  214,  412,  214,  412,  432,  442,

      423,  214,  432,  415,  452,  438,  416,  443,  426,  237,
      214,   32,   32,  221,  453,  375,   32,   32,  214,   32,
      517,   74,  431,  434,   32,  238,  238,  238,  446,   32,
      432,   32,  238,  238,  236,  236,  238,  238,  238,  238,
      238,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  237,  236,   32,  239,  240,  241,  242,  243,  214,
      244,  245,  246,  214,  214,  450,  245,  247,  248,  249,
      214,  433,  427,  214,  214,  432,  432,  429,  214,  454,
       74,  375,  428,  514,  351,  430,  432,  455,  458,  214,
      432,  250,  251,  252,  253,  254,  255,  214,  256,  257,

      258,  432,  437,  449,  257,  259,  260,  261,  463,  432,
      473,  465,  478,  476,  438,  450,  474,  286,  464,  466,
      479,  200,  474,  477,  214,  351,  351,  506,  284,  262,
      263,  264,  265,  266,  267,  284,  268,  269,  270,  482,
      506,  284,  269,  271,  272,  273,  284,  506,  284,  284,
      284,  284,  284,  489,   35,  351,  511,  287,  490,  512,
      499,  504,  505,  507,  506,  506,   93,  274,  282,  283,
      284,  285,  286,  351,  287,  288,  289,  287,  287,  287,
      288,  290,  291,  292,  287,  506,  506,  506,  351,  351,
      351,  351,  506,  329,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  507,  505,  293,  196,  196,  197,  392,
      197,  504,  197,  197,  196,  284,  499,  490,  197,  196,
      197,  196,  489,  488,   74,  474,  481,  480,  474,  475,
      472,  471,  470,  469,  468,  467,  462,  461,  460,  459,
      457,  450,  456,  196,  396,  397,  398,  399,  202,  450,
      203,  204,  400,  451,  448,  447,  204,  401,  402,  403,
      445,  444,  438,  438,  439,  436,  435,  433,  431,  214,
      426,  416,  415,  413,  411,  410,  200,  405,  395,  394,
      393,  404,  210,  210,  211,  210,  211,  388,  211,  211,
      210,  387,  386,  381,  211,  210,  211,  210,  382,  379,

      378,  376,  375,  374,  373,  369,  370,  367,  366,  364,
      363,  362,  357,  358,  355,  354,  352,  351,  350,  210,
      417,  418,  419,  420,  216,  349,  217,  218,  421,  345,
      346,  343,  218,  422,  423,  424,  342,  340,  339,  338,
      333,  333,  331,  330,  329,  328,  327,  326,  325,  320,
      319,  318,  316,  315,  314,  307,  309,  425,   32,  307,
      306,  304,   32,   32,  303,   32,  302,  294,  297,  295,
       32,  294,   87,  281,   74,   32,  277,   32,   74,  107,
       94,   93,   35,   88,   87,   86,   85,   83,   82,   73,
       71,   35,   55,   45,  518,  518,  518,  237,  518,   32,

      491,  492,  493,  494,  286,  518,  287,  288,  495,  518,
      518,  518,  288,  496,  291,  497,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  498,   32,  518,
      518,   32,   74,  518,  518,   74,   74,   75,   75,  236,
      518,  518,  236,  236,  237,  237,  197,  197,  197,  197,
      197,  211,  211,  518,  211,  211,    3,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518
    } ;

static yyconst short int yy_chk[1210] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    8,    8,    8,    8,  517,    8,    8,
        8,   12,   15,   12,    8,    8,    8,    8,   14,   15,
       15,   15,   14,   12,   16,   21,   25,  514,   25,   16,
       14,   26,   28,   26,   31,   16,   54,   21,   28,    8,
       10,   10,   10,   10,   10,  513,   10,   10,   10,   18,
       18,   18,   10,   10,   10,   10,   27,   31,   37,   18,

       27,   27,   38,   44,   64,   64,   64,   46,   37,   47,
       38,   54,   49,   76,   76,   50,   18,   10,   17,   46,
       91,   47,   17,   17,   49,   17,   44,   50,   91,   17,
       17,   17,   17,   17,   77,   17,   77,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       23,   51,   52,   53,   23,   23,   65,   23,   60,   60,
       60,  277,   23,   51,   52,   53,   60,   23,   80,   23,
      277,   80,   60,   65,   66,   66,   70,   70,   70,   81,
       82,   85,   81,   82,   66,   89,   70,  498,   86,   23,

       88,   23,   24,   85,  106,   89,   24,   24,   90,   24,
       86,   66,   88,   70,   24,   92,   93,   94,   90,   24,
       97,   24,  100,   92,   93,   94,   99,  106,  111,  107,
      100,  108,   97,  488,  114,   24,   99,  107,  120,  113,
      111,   24,  114,   24,   42,   42,   42,   42,   42,  113,
       42,   42,   42,  125,  108,  137,   42,   42,   42,   42,
      126,  120,  133,  125,  134,  139,  140,  137,  126,  146,
      133,  275,  152,  275,  140,  139,  404,  158,  487,  149,
      152,   42,   45,   45,   45,   45,   45,  170,   45,   45,
       45,  149,  146,  161,   45,   45,   45,   45,  163,  134,

      158,  164,  173,  175,  185,  161,  182,  187,  163,  164,
      170,  404,  484,  175,  173,  228,  185,  187,  194,   45,
       48,   48,   48,   48,   48,  228,   48,   48,   48,  182,
      188,  209,   48,   48,   48,   48,  203,  195,  188,  195,
      203,  194,  195,  195,  195,  279,  223,  393,  203,  279,
      425,  202,  393,  202,  209,  207,  221,   48,   55,   55,
       55,   55,   55,  202,   55,   55,   55,  207,  221,  223,
       55,   55,   55,   55,  216,  217,  216,  226,  235,  217,
      229,  241,  243,  244,  250,  425,  216,  217,  229,  226,
      470,  244,  243,  241,  461,   55,   56,   56,   56,   56,

       56,  235,   56,   56,   56,  255,  256,  250,   56,   56,
       56,   56,  265,  267,  256,  255,  274,  268,  287,  291,
      276,  280,  287,  267,  265,  268,  276,  405,  280,  305,
      287,  291,  296,   56,   57,   57,   57,   57,   57,  274,
       57,   57,   57,  286,  296,  286,   57,   57,   57,   57,
      298,  300,  305,  308,  310,  286,  332,  392,  312,  300,
      298,  323,  336,  376,  310,  308,  312,  317,  332,  323,
      336,   57,   58,   58,   58,   58,   58,  341,   58,   58,
       58,  321,  334,  344,   58,   58,   58,   58,  347,  356,
      317,  321,  334,  359,  360,  344,  347,  353,  365,  375,

      341,  356,  360,  359,  377,  371,  374,  368,  389,   58,
       59,   59,   59,   59,   59,  371,   59,   59,   59,  368,
      353,  365,   59,   59,   59,   59,  380,  377,  385,  383,
      373,  389,  390,  390,  390,  440,  385,  372,  380,  383,
      391,  391,  391,  483,  370,  440,  483,   59,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       62,   62,  369,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   63,   63,   63,   63,   63,  394,   63,   63,
       63,  395,  396,  397,   63,   63,   63,   63,  400,  394,
      399,  401,  402,  395,  396,  397,  399,  486,  486,  403,
      400,  407,  399,  401,  402,  414,  406,  409,  406,   63,
       67,  403,  408,  407,   67,   67,  408,   67,  406,  409,
      410,  411,   67,  412,  408,  413,  415,   67,  414,   67,
      416,  417,  410,  411,  418,  412,  420,  413,  415,  442,

      434,  421,  416,  417,  452,  446,  418,  442,  420,   67,
      422,   67,   68,  421,  452,  367,   68,   68,  423,   68,
      515,  515,  422,  434,   68,   68,   68,   68,  446,   68,
      423,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   71,   71,   71,   71,   71,  424,
       71,   71,   71,  426,  428,  458,   71,   71,   71,   71,
      427,  424,  427,  429,  430,  426,  428,  429,  431,  454,
      485,  366,  427,  485,  352,  429,  430,  454,  458,  432,
      431,   71,   72,   72,   72,   72,   72,  433,   72,   72,

       72,  432,  437,  449,   72,   72,   72,   72,  463,  433,
      473,  465,  478,  476,  437,  449,  482,  501,  463,  465,
      478,  511,  473,  476,  512,  351,  350,  501,  489,   72,
       73,   73,   73,   73,   73,  490,   73,   73,   73,  482,
      489,  491,   73,   73,   73,   73,  492,  490,  494,  495,
      496,  497,  499,  491,  510,  349,  511,  503,  492,  512,
      494,  495,  496,  497,  499,  503,  510,   73,   84,   84,
       84,   84,   84,  348,   84,   84,   84,  504,  505,  506,
       84,   84,   84,   84,  507,  504,  505,  506,  346,  345,
      343,  342,  507,  329,  328,  327,  326,  325,  324,  322,

      320,  319,  318,  292,  290,   84,  196,  196,  196,  196,
      196,  289,  196,  196,  196,  288,  285,  283,  196,  196,
      196,  196,  282,  281,  278,  273,  271,  270,  269,  266,
      264,  263,  262,  261,  259,  258,  254,  253,  252,  251,
      249,  247,  246,  196,  200,  200,  200,  200,  200,  245,
      200,  200,  200,  242,  240,  239,  200,  200,  200,  200,
      234,  232,  231,  230,  227,  225,  224,  222,  220,  218,
      215,  213,  212,  208,  206,  205,  204,  201,  199,  198,
      197,  200,  210,  210,  210,  210,  210,  193,  210,  210,
      210,  191,  190,  189,  210,  210,  210,  210,  186,  184,

      183,  181,  180,  179,  178,  177,  174,  172,  171,  169,
      167,  166,  165,  162,  160,  159,  157,  156,  155,  210,
      214,  214,  214,  214,  214,  154,  214,  214,  214,  153,
      150,  148,  214,  214,  214,  214,  147,  145,  143,  142,
      141,  138,  136,  135,  132,  131,  130,  129,  128,  124,
      122,  121,  119,  117,  116,  115,  112,  214,  236,  110,
      109,  105,  236,  236,  103,  236,  102,  101,   98,   96,
      236,   95,   87,   83,   79,  236,   78,  236,   74,   43,
       41,   40,   39,   36,   35,   34,   33,   30,   29,   22,
       20,   19,   11,    9,    3,    0,    0,  236,    0,  236,

      284,  284,  284,  284,  284,    0,  284,  284,  284,    0,
        0,    0,  284,  284,  284,  284,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  284,  519,    0,
        0,  519,  520,    0,    0,  520,  520,  521,  521,  522,
        0,    0,  522,  522,  523,  523,  524,  524,  524,  524,
      524,  525,  525,    0,  525,  525,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include "tn.h"
	#include "symtable.h"
#line 806 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 8 "scanner.l"

#line 959 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 519 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1167 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "scanner.l"
return(TCONST);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 "scanner.l"
return(TELSE);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "scanner.l"
return(TIF);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 "scanner.l"
return(TINT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 "scanner.l"
return(TRETURN);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 "scanner.l"
return(TVOID);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "scanner.l"
return(TFLOAT);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 "scanner.l"
return(TWHILE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 "scanner.l"
return(TEQUAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 "scanner.l"
return(TNOTEQU);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 "scanner.l"
return(TLESSE);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 "scanner.l"
return(TGREATE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "scanner.l"
return(TAND);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "scanner.l"
return(TOR);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 "scanner.l"
return(TINC);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 24 "scanner.l"
return(TDEC);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 25 "scanner.l"
return(TADDASSIGN);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 26 "scanner.l"
return(TSUBASSIGN);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 27 "scanner.l"
return(TMULASSIGN);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 28 "scanner.l"
return(TDIVASSIGN);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 29 "scanner.l"
return(TMODASSIGN);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 30 "scanner.l"
return(TDIV);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 31 "scanner.l"
return(TMULTI);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 32 "scanner.l"
return(TLESS);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 33 "scanner.l"
return(TMORE);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 34 "scanner.l"
return(TERROR);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 35 "scanner.l"
return(TMOD);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 36 "scanner.l"
return(TERROR);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 37 "scanner.l"
return(TERROR);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 38 "scanner.l"
return(TSEMICOLON);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 39 "scanner.l"
return(TPLUS);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 40 "scanner.l"
return(TMINUS);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 41 "scanner.l"
return(TDOT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 42 "scanner.l"
return(TCOMMA);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 43 "scanner.l"
return(TASSIGN);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 45 "scanner.l"
return(TINTEGER);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 46 "scanner.l"
return (TREALNUM); // report error except for floating point
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "scanner.l"
{ printf("Error - start with digit\n"); return (TERROR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 50 "scanner.l"
{
	int symbol_num = lookup_sym_table(yytext);
	if (symbol_num != -1) { // already in symbol table
		return(TIDENT);
	}
	if (yyleng >= 15) {
		printf("Error - too long identifier\n");
		return (TERROR);
	}
	if (check_strpool_overflow(yytext)) { // string pool overflow 
		printf("Error - Strpool_Overflow\n"); 
		return (TERROR);
	}
	if (check_symtable_overflow()) { // symboltable overflow
		printf("Error - Symtable_Overflow\n");
		return (TERROR);
	} 
	// didn't include hashtable overflow because it's handled by backward method

	int val = validate_identifier(yytext);

    if (val == 1) {
		process_symbol(yytext, TIDENT);
		return(TIDENT);
    } 
}
	YY_BREAK
case 40:
#line 78 "scanner.l"
case 41:
#line 79 "scanner.l"
case 42:
#line 80 "scanner.l"
case 43:
#line 81 "scanner.l"
case 44:
#line 82 "scanner.l"
case 45:
#line 83 "scanner.l"
case 46:
#line 84 "scanner.l"
case 47:
#line 85 "scanner.l"
case 48:
#line 86 "scanner.l"
case 49:
#line 87 "scanner.l"
case 50:
#line 88 "scanner.l"
case 51:
#line 89 "scanner.l"
case 52:
YY_RULE_SETUP
#line 89 "scanner.l"
{ printf("Error - illegal identifier\n"); return(TERROR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "scanner.l"
{ printf("Error - illegal identifier\n"); return(TERROR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "scanner.l"
return(TNEWLINE);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "scanner.l"
;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "scanner.l"
;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "scanner.l"
;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "scanner.l"
return(yytext[0]);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "scanner.l"
ECHO;
	YY_BREAK
#line 1326 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 519 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 519 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 518);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( _fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 100 "scanner.l"

extern lookup_sym_table(char* str);
int yywrap() 
{
	printf(" End of Lex\n");
	return 1;
}