enum tnumber { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, TNOTEQU, TLESSE, TGREATE, 
								TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TDOT, TCOMA, TASSIGN, TFLOAT,
								TIDENT, TSEMICOLON, TPLUS, TMINUS, TINTEGER, TREALNUM, TNUMBER, TNEWLINE, TERROR
};